# Helm config
mixer:
  hostProject: datcom-mixer-autopush
  serviceName: autopush.api.datacommons.org

ingress:
  enabled: true
  name: mixer-ingress-autopush
  annotations:
    {
      ingress.gcp.kubernetes.io/pre-shared-cert: "mixer-certificate,multi-domain-2022",
    }

# GCP level config.
ip: 34.117.145.125
region: us-central1
api_title: DataCommons API (Autopush)
nodes: 4

serviceGroups:
  svg:
      replicas: 5
  recon:
      replicas: 20
  observation:
      replicas: 20
  node:
      replicas: 20
  default:
      replicas: 10